### ISSUE TITLE
请问怎么取消懒加载，需要看到所有题目？

### ISSUE THREAD

**Issue by anonymous12357** [serfend/problem-killer#67]
你好，请问在哪个文件代码里面可以取消题目懒加载，因为一次显示4个太少了，有时候要看题目多少决定分配

**Comment by serfend** [comment]
可以在设置里面把显示题目的数量增大，但随着一次显示题目数量的变多，也可能会导致屏幕变卡

**Comment by serfend** [comment]
![image](https://user-images.githubusercontent.com/20139227/209521391-984a3be7-56e9-46cb-ae18-77a19d2c8852.png)
